### ISSUE TITLE
Les 6 final

### ISSUE THREAD

**Issue by aschwinwester** [DianaHuisen/Programming1#3]
1. Weekend is een boolean.
Je kan een functie maken welke naar een dag vraagt en bijvoorbeeld.
dag.lower()[0] == 'z'

2. Je kan de korting berekening en dan later de ritprijs.
3. de ritprijs functie geeft de ritprijs terug. Daarna kan je het printen.
4. Ik zie geen test functies.

**Comment by DianaHuisen** [comment]
1. dit is gefixt.
2. als ik nog speciaal een variabele moet aanmaken om de korting te berekenen om daarna pas de ritprijs te gaan berekenen, krijg je overbodige code aangezien je het ook kan samenvoegen tot 1 berekening. 
3. Fixed.
4. Dat is omdat dat super overbodig is, want ik test alles handmatig. Het zijn inputs dus ik ga alles met de hand testen, ik kijk per lengte, per leeftijd en per dag of het binnen/buiten een categorie valt en als het dan werkt, dan is het goed. Werkt het niet, dan moet het aangepast worden. Zo werkt testen... Ik ga hier echt geen aparte functie voor aanmaken, want dat is overbodig en mijn code werkt gewoon.
