### ISSUE TITLE
les 9: 4.File&Dict.py

### ISSUE THREAD

**Issue by aschwinwester** [DianaHuisen/Programming1#7]
Je doet in de functie ticker() niks met:

-  de parameter en
-  ook niks met de return waarde.
De code werkt, neem ik aan, maar niet zoals het eigenlijk zou moeten.

**Comment by DianaHuisen** [comment]
Ik vul dictionary in op de plaats van filename (parameter) en de return waarde zorgt ervoor dat als je het programma runt, dat je dan te zien krijgt wat waarbij hoort. dit had ik gedaan om het testen voor mezelf wat makkelijker te maken, aangezien erboven dus de mogelijkheden staan.
